"""Compare MontuPython planetary ephemerides against the organic snapshot.

The reference CSV is generated by ``bin/generate_organic_planetary_ephemeris.py``
and encodes geocentric positions for Sun, Moon, and the classical planets with
quarterly samples in one year per Saros cycle from 3000 BCE to 1599 CE.
Regenerate the snapshot after intentional ephemeris or catalogue changes.
"""

from __future__ import annotations

import pytest

from montu.tests.organic_snapshot_support import (
    PLANETARY_BODIES,
    PLANETARY_ORGANIC_CSV,
    PLANETARY_SAMPLES_PER_YEAR,
    compute_planetary_row,
    geocentric_observer as make_geocentric_observer,
    planetary_saros_sample_years,
    read_organic_csv,
)

ABS_TOL = 1e-6
REL_TOL = 1e-9


@pytest.fixture(scope="module")
def organic_planetary_snapshot():
    metadata, rows = read_organic_csv(PLANETARY_ORGANIC_CSV)
    assert rows, "organic planetary snapshot is empty"
    return metadata, rows


@pytest.fixture(scope="module")
def geocentric_observer():
    return make_geocentric_observer()


def test_organic_planetary_snapshot_metadata(organic_planetary_snapshot):
    import ephem

    metadata, rows = organic_planetary_snapshot
    assert metadata.get("montu_version")
    assert metadata.get("generated")
    assert metadata.get("pyephem_version") == ephem.__version__
    expected_rows = (
        len(planetary_saros_sample_years())
        * len(PLANETARY_SAMPLES_PER_YEAR)
        * len(PLANETARY_BODIES)
    )
    assert len(rows) == expected_rows
    if metadata.get("row_count"):
        assert int(metadata["row_count"]) == expected_rows


def test_planetary_ephemeris_matches_organic_snapshot(
    organic_planetary_snapshot,
    geocentric_observer,
):
    _, rows = organic_planetary_snapshot
    for row in rows:
        computed = compute_planetary_row(
            row["Name"].strip(),
            row["Date and Time"].strip(),
            geocentric_observer,
        )
        label = f"{row['Name']} @ {row['Date and Time']}"
        for key in ("RAJ2000", "DecJ2000", "Mag", "Phase", "Dist_AU"):
            ref = float(row[key])
            val = float(computed[key])
            assert val == pytest.approx(ref, rel=REL_TOL, abs=ABS_TOL), (
                f"{label}: {key} snapshot={ref}, montu={val}"
            )
