"""Compare MontuPython stellar positions against the organic snapshot.

The reference CSV is generated by ``bin/generate_organic_stellar_positions.py``
and encodes Sirius and Canopus every 100 years from 3000 BCE to 1600 CE at the
Thebes-like site used in ``test_stellar_positions.py``. Regenerate the snapshot
after intentional catalogue or precession changes.
"""

from __future__ import annotations

import montu
import pytest

from montu.tests.organic_snapshot_support import (
    STELLAR_ORGANIC_CSV,
    compute_stellar_row,
    load_star,
    read_organic_csv,
    thebes_like_observer as make_thebes_like_observer,
)

ABS_TOL = 1e-6
REL_TOL = 1e-9
TIME_TOL_SEC = 1.0


def _time_diff_seconds(computed: str, reference: str) -> float:
    jed_a = montu.Time(computed.strip(), calendar="proleptic").jed
    jed_b = montu.Time(reference.strip(), calendar="proleptic").jed
    return abs(jed_a - jed_b) * montu.DAY


@pytest.fixture(scope="module")
def organic_stellar_snapshot():
    metadata, rows = read_organic_csv(STELLAR_ORGANIC_CSV)
    assert rows, "organic stellar snapshot is empty"
    return metadata, rows


@pytest.fixture(scope="module")
def thebes_observer():
    return make_thebes_like_observer()


@pytest.fixture(scope="module")
def star_catalogues():
    return {name: load_star(name) for name in ("Sirius", "Canopus")}


def test_organic_stellar_snapshot_metadata(organic_stellar_snapshot):
    import ephem

    metadata, rows = organic_stellar_snapshot
    assert metadata.get("montu_version")
    assert metadata.get("generated")
    if metadata.get("pyephem_version"):
        assert metadata["pyephem_version"] == ephem.__version__
    assert len(rows) == 92


def test_stellar_positions_match_organic_snapshot(
    organic_stellar_snapshot,
    thebes_observer,
    star_catalogues,
):
    _, rows = organic_stellar_snapshot
    float_fields = (
        "RAJ2000",
        "DecJ2000",
        "RAJ2000t",
        "DecJ2000t",
        "RAEpoch",
        "DecEpoch",
        "az",
        "el",
        "Transit_el_deg",
    )
    for row in rows:
        name = row["Name"].strip()
        era = row["Era"].strip()
        year = int(row["Historical_Year"])
        star, catalogue = star_catalogues[name]
        computed = compute_stellar_row(
            name,
            era,
            year,
            star,
            catalogue.data.iloc[0],
            thebes_observer,
        )
        label = f"{name} {era} {year}"

        for key in float_fields:
            ref = float(row[key])
            val = float(computed[key])
            assert val == pytest.approx(ref, rel=REL_TOL, abs=ABS_TOL), (
                f"{label}: {key} snapshot={ref}, montu={val}"
            )

        for key in ("Rise", "Transit", "Set"):
            diff = _time_diff_seconds(computed[key], row[key])
            assert diff <= TIME_TOL_SEC, (
                f"{label}: {key} snapshot={row[key]}, montu={computed[key]}, "
                f"diff={diff:.3f} s"
            )
